spring:
  datasource:
        url: jdbc:mysql://192.168.1.116:3306/fomo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 'fbee#55#'
        max-idle: 10
        max-wait: 1000
        min-idle: 5
        initial-size: 5
  redis:
        host: 127.0.0.1
        port: 6379
        timeout: 3000
        max-idle: 200
        max-active: 2000
        max-wait: 1000
log:
  path: /usr/local/data/tomcat7/oneeth/logs/
  name: oneeth_game
  commonLevel: INFO
  springLevel: INFO 