spring:
  datasource:
        url: jdbc:mysql://52.8.143.175:3306/test_bee_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
        driver-class-name: com.mysql.jdbc.Driver
        username: fbee
        password: 'fbee#55#'
        max-idle: 10
        max-wait: 1000
        min-idle: 5
        initial-size: 5
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 2000
      max-wait: 1000
      max-idle: 200
      min-idle: 0
    timeout: 3000
log:
  path: /usr/local/
  name: oneeth_game
  commonLevel: INFO
  springLevel: INFO 